const EXPANDED_ACTORS = {
  "Tom Hanks": ["Meg Ryan"],
  "Leonardo DiCaprio": ["Tom Hardy"],
  "Meryl Streep": ["Amy Adams"],
  "Robert De Niro": ["Al Pacino"],
  "Scarlett Johansson": ["Chris Evans"],
  "Brad Pitt": ["Edward Norton"],
  "Angelina Jolie": ["Elle Fanning"],
  "Denzel Washington": ["Viola Davis"],
  "Johnny Depp": ["Helena Bonham Carter"],
  "Jennifer Lawrence": ["Bradley Cooper"],
  "Morgan Freeman": ["Tim Robbins"],
  "Nicole Kidman": ["Hugh Jackman"],
  "Will Smith": ["Margot Robbie"],
  "Natalie Portman": ["Mila Kunis"],
  "Christian Bale": ["Amy Adams"],
  "Julia Roberts": ["George Clooney"],
  "George Clooney": ["Matt Damon"],
  "Matt Damon": ["Ben Affleck"],
  "Anne Hathaway": ["Meryl Streep"],
  "Hugh Jackman": ["Anne Hathaway"],
  "Keanu Reeves": ["Sandra Bullock"],
  "Sandra Bullock": ["Ryan Reynolds"],
  "Ryan Reynolds": ["Blake Lively"],
  "Emma Stone": ["Ryan Gosling"],
  "Ryan Gosling": ["Emma Stone"],
  "Harrison Ford": ["Carrie Fisher"],
  "Chris Hemsworth": ["Natalie Portman"],
  "Tom Cruise": ["Nicole Kidman"],
  "Charlize Theron": ["Tom Hardy"],
  "Benedict Cumberbatch": ["Martin Freeman"],
  "Tom Hardy": ["Cillian Murphy"],
  "Amy Adams": ["Jeremy Renner"],
  "Jake Gyllenhaal": ["Heath Ledger"],
  "Chris Evans": ["Scarlett Johansson"],
  "Robert Downey Jr.": ["Gwyneth Paltrow"],
  "Mark Ruffalo": ["Jennifer Garner"],
  "Gal Gadot": ["Chris Pine"],
  "Ben Affleck": ["Henry Cavill"],
  "Henry Cavill": ["Amy Adams"],
  "Margot Robbie": ["Jared Leto"],
  "Joaquin Phoenix": ["Zazie Beetz"],
  "Reese Witherspoon": ["Laura Dern"],
  "Jennifer Aniston": ["Adam Sandler"],
  "Adam Sandler": ["Drew Barrymore"],
  "Drew Barrymore": ["Cameron Diaz"],
  "Cameron Diaz": ["Lucy Liu"],
  "Lucy Liu": ["Jonny Lee Miller"],
  "Viola Davis": ["Octavia Spencer"],
  "Octavia Spencer": ["Jessica Chastain"],
  "Jessica Chastain": ["Oscar Isaac"],
};
module.exports = EXPANDED_ACTORS;
