export const popularActors = [
  { id: 1, name: "Leonardo DiCaprio", image: "/images/leonardo.jpg" },
  { id: 2, name: "Samuel L. Jackson", image: "/images/samuelljackson.jpg" },
  { id: 3, name: "Brad Pitt", image: "/images/brad_pitt.webp" },
  { id: 4, name: "Margot Robbie", image: "/images/margot.jpg" },
  { id: 5, name: "Robert Downey Jr.", image: "/images/robert_downey_jr.jpg" },
  { id: 6, name: "Morgan Freeman", image: "/images/morgan_freeman.jpg" },
  { id: 7, name: "Cillian Murphy", image: "/images/cillian_murphy.webp" },
  { id: 8, name: "Jake Gylenhaal", image: "/images/gyllenhaal.jpg" },
  { id: 9, name: "Jason Statham", image: "/images/jason_statham.jpg" },
  { id: 10, name: "Johny Depp", image: "/images/johny_depp.jpg" },
  { id: 11, name: "Emma Stone", image: "/images/emma_stone.jpg" },
  { id: 12, name: "Keanu Reeves", image: "/images/keanu_reeves.jpg" },
  { id: 13, name: "Matthew McConaughey", image: "/images/mathew.jpg" },
  { id: 14, name: "Sandra Bullock", image: "/images/bullock.webp" },
  { id: 15, name: "Christian Bale", image: "/images/christian_bale.jpg" },
  { id: 16, name: "Ryan Gosling", image: "/images/ryan_gosling.jpg" },
  { id: 17, name: "Ryan Reynolds", image: "/images/ryan_reynolds.jpg" },
  { id: 18, name: "Meryl Streep", image: "/images/meryl_streep.jpg" },
  { id: 19, name: "Jesse Eisenberg", image: "/images/jesse_eisenberg.jpeg" },
  { id: 20, name: "Nicole Kidman", image: "/images/kidman.webp" },
  { id: 21, name: "Timothée Chalamet", image: "/images/chalamet.webp" },
  { id: 22, name: "Clint Eastwood", image: "/images/eastwood.jpg" },
  { id: 23, name: "Al Pacino", image: "/images/alpacino.jpg" },
  { id: 24, name: "William Dafoe", image: "/images/dafoe.jpg" },
  { id: 25, name: "Kate Winslet", image: "/images/winslet.jpg" },
  { id: 26, name: "Marilyn Monroe", image: "/images/monroe.jpeg" },
  { id: 27, name: "Adam Sandler", image: "/images/sandler.jpg" },
  { id: 28, name: "Zendaya", image: "/images/zendaya.webp" },
  { id: 29, name: "Adam Driver", image: "/images/driver.jpg" },
  { id: 30, name: "Robert Pattinson", image: "/images/pattinson.jpg" },
  { id: 31, name: "Jamie Foxx", image: "/images/foxx.jpg" },
  { id: 32, name: "Jim Carrey", image: "/images/carrey.webp" },
  { id: 33, name: "Tom Holland", image: "/images/holland.webp" },
];
