export const popularDirectors = [
  { id: 1, name: "Christopher Nolan", image: "/images/nolan.jpg" },
  { id: 2, name: "Quentin Tarantino", image: "/images/tarantino.jpeg" },
  { id: 3, name: "Martin Scorsese", image: "/images/scorsese.webp" },
  { id: 4, name: "Steven Spielberg", image: "/images/spielberg.jpg" },
  { id: 5, name: "James Cameron", image: "/images/cameron.jpg" },
  { id: 6, name: "Ridley Scott", image: "/images/scott.jpg" },
  { id: 7, name: "David Fincher", image: "/images/fincher.jpg" },
  { id: 8, name: "Stanley Kubrick", image: "/images/kubrick.jpg" },
  { id: 9, name: "Alfred Hitchcock", image: "/images/hitchcock.png" },
  { id: 10, name: "Denis Villeneuve", image: "/images/villeneuve.jpg" },
  { id: 11, name: "Darren Aronofsky", image: "/images/aronofsky.jpg" },
  { id: 12, name: "Roman Polanski", image: "/images/polanski.jpeg" },
  { id: 13, name: "Peter Jackson", image: "/images/jackson.jpg" },
  { id: 14, name: "Zack Snyder", image: "/images/snyder.jpg" },
  { id: 15, name: "M. Night Shyamalan", image: "/images/shyamalan.jpg" },
  { id: 16, name: "Tim Burton", image: "/images/burton.jpg" },
  { id: 17, name: "Wes Anderson", image: "/images/anderson.jpg" },
  { id: 18, name: "Andrzej Wajda", image: "/images/wajda.jpg" },
  { id: 19, name: "Orson Welles", image: "/images/welles.jpg" },
  { id: 20, name: "Woody Allen", image: "/images/allen.jpg" },
];
